### ISSUE TITLE
Fake emails break the site via Mailchimp API

### ISSUE THREAD

**Issue by wsf246** [projectcredo/projectcredo#59]
**Problem:** Describe the problem here.
Mailchimp rejects fake looking emails like user@example.com.  On production this will break the site completely.
**Steps to Reproduce:** If it's a bug, please detail the steps required to reproduce it.
Create a user on staging like user1@example.com and the site will break.
**Desired Outcome:** What would you like to happen?
We should probably throw an error message instead?
**Other Notes or Comments:**

**Comment by briankung** [comment]
This is one reason why a job queue would be useful.

**Comment by wsf246** [comment]
closed by #58
